"""Default runtime values and safety limits."""

DEFAULT_RESPONSE_TIMEOUT = 180
DEFAULT_STABLE_CHECKS = 4
DEFAULT_STABLE_INTERVAL = 2.5

DEFAULT_BATCH_SIZE = 25
DEFAULT_TARGET_COUNT = 100

MAX_ITERATIONS = 25
MAX_EMPTY_STREAK = 4
MAX_REPAIR_ATTEMPTS = 2

MAX_EXCLUDED_URLS_IN_PROMPT = 100

# Runtime mode controls
DEFAULT_RUNTIME_MODE = "ui"
DEFAULT_BROWSER_MODE = "attach"
DEFAULT_HEADLESS = False
DEFAULT_CHROME_USER_DATA_DIR = "/tmp/chrome-debug-profile"

# API model and retry defaults
DEFAULT_GEMINI_PRIMARY_MODEL = "gemini-3.1-pro"
DEFAULT_GEMINI_FALLBACK_MODELS = ["gemini-3-flash", "gemini-3.1-flash-lite"]
DEFAULT_GEMINI_TEMPERATURE = 0.2
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS = 8192

DEFAULT_API_MAX_RETRIES = 4
DEFAULT_API_BACKOFF_MIN_SECONDS = 1.0
DEFAULT_API_BACKOFF_MAX_SECONDS = 16.0

# Long-run orchestration defaults
DEFAULT_INTER_ROUND_SLEEP_MIN = 45
DEFAULT_INTER_ROUND_SLEEP_MAX = 90
DEFAULT_CONTEXT_RESET_INTERVAL = 15
DEFAULT_SCREENSHOT_INTERVAL = 10
DEFAULT_MEMORY_CLEAN_INTERVAL = 20
