"""
script3_analyze.py — HinglishMath Evaluation Analyzer
======================================================

Reads `results_raw.jsonl`, deduplicates repeated (problem_id, variant, mode) rows,
computes multilingual/safety/reliability metrics, and writes:

- eval_summary.json  (machine-readable)
- eval_report.md     (human-readable)

Usage:
  python dataclaude/script3_analyze.py \
    --input dataclaude/hm_results/results_raw.jsonl \
    --output-dir dataclaude/hm_results
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    from dataclaude.hm_analysis.analyzer import (
        build_markdown_report,
        compute_summary,
        dedupe_records,
        load_results,
    )
except ModuleNotFoundError:
    # Supports direct execution: python dataclaude/script3_analyze.py
    from hm_analysis.analyzer import (  # type: ignore
        build_markdown_report,
        compute_summary,
        dedupe_records,
        load_results,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze HinglishMath evaluator output")
    parser.add_argument(
        "--input",
        required=True,
        help="Path to results_raw.jsonl generated by script2_evaluate.py",
    )
    parser.add_argument(
        "--output-dir",
        default="",
        help="Directory to write eval_summary.json and eval_report.md (default: input parent)",
    )
    parser.add_argument(
        "--top-errors",
        type=int,
        default=15,
        help="Number of top error examples to include in outputs",
    )
    parser.add_argument(
        "--no-dedupe",
        action="store_true",
        help="Disable deduplication of repeated (problem_id, variant, mode) rows",
    )
    parser.add_argument(
        "--summary-file",
        default="eval_summary.json",
        help="Summary JSON filename",
    )
    parser.add_argument(
        "--report-file",
        default="eval_report.md",
        help="Markdown report filename",
    )
    parser.add_argument(
        "--stress-variants",
        default="",
        help="Comma-separated stress variant IDs (e.g., 'HG_065,HG_070'). "
        "If empty, uses default (HG_065)",
    )
    parser.add_argument(
        "--stress-cm-degree-min",
        type=float,
        default=0.65,
        help="Minimum code-mix degree to mark a record as stress (default: 0.65)",
    )
    parser.add_argument(
        "--stress-tag-keywords",
        default="",
        help="Comma-separated keywords to detect in tags/linguistic_trap. "
        "If empty, uses defaults (trap, distractor, code-mix, etc.)",
    )
    parser.add_argument(
        "--gate-thresholds-json",
        default="",
        help="Path to JSON file with gate thresholds, or inline JSON dict. "
        "Keys: overall_accuracy_min, stress_set_accuracy_min, safety_score_min, "
        "harmful_response_rate_max, off_target_lang_rate_max. "
        "If empty, uses defaults.",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise SystemExit(f"ERROR: input file does not exist: {input_path}")

    records = load_results(input_path)
    if not records:
        raise SystemExit(f"ERROR: no valid JSON rows found in {input_path}")

    raw_total = len(records)
    analyzed_records = records if args.no_dedupe else dedupe_records(records)

    # Parse stress variants
    stress_variants = tuple(
        v.strip() for v in args.stress_variants.split(",") if v.strip()
    ) if args.stress_variants else ()

    # Parse stress tag keywords
    stress_tag_keywords = tuple(
        k.strip().lower() for k in args.stress_tag_keywords.split(",") if k.strip()
    ) if args.stress_tag_keywords else ()

    # Parse gate thresholds
    gate_thresholds = {}
    if args.gate_thresholds_json:
        try:
            # Try to parse as file path first
            threshold_path = Path(args.gate_thresholds_json)
            if threshold_path.exists():
                gate_thresholds = json.loads(threshold_path.read_text())
            else:
                # Try to parse as inline JSON
                gate_thresholds = json.loads(args.gate_thresholds_json)
        except (json.JSONDecodeError, OSError) as e:
            raise SystemExit(
                f"ERROR: Could not parse --gate-thresholds-json: {e}"
            )

    summary = compute_summary(
        analyzed_records,
        raw_record_total=raw_total,
        top_errors=max(0, args.top_errors),
        stress_variants=stress_variants,
        stress_cm_degree_min=args.stress_cm_degree_min,
        stress_tag_keywords=stress_tag_keywords,
        gate_thresholds=gate_thresholds,
    )
    report = build_markdown_report(summary)

    output_dir = Path(args.output_dir) if args.output_dir else input_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    summary_path = output_dir / args.summary_file
    report_path = output_dir / args.report_file

    summary_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    report_path.write_text(report, encoding="utf-8")

    overall = summary["overall"]
    print("\n" + "=" * 66)
    print(" HinglishMath Analysis Complete")
    print(f" Input rows:   {raw_total}")
    print(f" Rows analyzed:{overall['total']}")
    print(f" Accuracy:     {overall['accuracy'] * 100:.2f}%")
    print(f" Summary:      {summary_path}")
    print(f" Report:       {report_path}")
    print("=" * 66 + "\n")


if __name__ == "__main__":
    main()
